"""On update and default

Revision ID: 41659a4102f5
Revises: 489fefb9fdf0
Create Date: 2024-10-13 15:21:52.717251

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "41659a4102f5"
down_revision: str | None = "489fefb9fdf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
