"""On update

Revision ID: 489fefb9fdf0
Revises: 81a33c1b8fa2
Create Date: 2024-10-13 15:21:03.592967

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "489fefb9fdf0"
down_revision: str | None = "81a33c1b8fa2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
