"""Initial Database Structure

Revision ID: 81a33c1b8fa2
Revises:
Create Date: 2024-10-13 15:11:37.475941

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81a33c1b8fa2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "albums",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("barcode", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("spotify_id", sa.String(), nullable=False),
        sa.Column("discogs_url", sa.String(), nullable=True),
        sa.Column("cover_image_url", sa.String(), nullable=True),
        sa.Column("last_update", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_albums_artist"), "albums", ["artist"], unique=True)
    op.create_index(op.f("ix_albums_barcode"), "albums", ["barcode"], unique=True)
    op.create_index(op.f("ix_albums_id"), "albums", ["id"], unique=False)
    op.create_index(op.f("ix_albums_name"), "albums", ["name"], unique=True)
    op.create_index(op.f("ix_albums_spotify_id"), "albums", ["spotify_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_albums_spotify_id"), table_name="albums")
    op.drop_index(op.f("ix_albums_name"), table_name="albums")
    op.drop_index(op.f("ix_albums_id"), table_name="albums")
    op.drop_index(op.f("ix_albums_barcode"), table_name="albums")
    op.drop_index(op.f("ix_albums_artist"), table_name="albums")
    op.drop_table("albums")
    # ### end Alembic commands ###
