"""More columns

Revision ID: cc8b2ba7302c
Revises: 41659a4102f5
Create Date: 2024-10-13 15:31:48.696795

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc8b2ba7302c"
down_revision: str | None = "41659a4102f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("albums", sa.Column("year", sa.String(), nullable=False))
    op.add_column("albums", sa.Column("genres", sa.String(), nullable=False))
    op.add_column("albums", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("albums", "is_deleted")
    op.drop_column("albums", "genres")
    op.drop_column("albums", "year")
    # ### end Alembic commands ###
