"""Artist and album name are nonunique

Revision ID: e3f41110a693
Revises: cc8b2ba7302c
Create Date: 2024-11-02 15:10:01.457244

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3f41110a693"
down_revision: str | None = "cc8b2ba7302c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_albums_artist", table_name="albums")
    op.create_index(op.f("ix_albums_artist"), "albums", ["artist"], unique=False)
    op.drop_index("ix_albums_name", table_name="albums")
    op.create_index(op.f("ix_albums_name"), "albums", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_albums_name"), table_name="albums")
    op.create_index("ix_albums_name", "albums", ["name"], unique=1)
    op.drop_index(op.f("ix_albums_artist"), table_name="albums")
    op.create_index("ix_albums_artist", "albums", ["artist"], unique=1)
    # ### end Alembic commands ###
